#include <stdio.h>

int main() {
    int num, reversed_num = 0, remainder, original_num;

    printf("Enter a number: ");
    scanf("%d", &num);

    original_num = num;

    // reverse the number
    while (num != 0) {
        remainder = num % 10;
        reversed_num = reversed_num * 10 + remainder;
        num /= 10;
    }

    if (original_num == reversed_num) {
        printf("%d is a palindrome number.", original_num);
    }
    else {
        printf("%d is not a palindrome number.", original_num);
    }

    return 0;
}
